version: '3.8'

services:
  hubi-mysql8-db:
    image: mysql:8.0.33
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: 'hubertspring'
      MYSQL_USER: 'hubi'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
    driver: local